OBJS = mytail	myls	mystat	mytree
CMD = cc

all: mytail	myls	mystat	mytree

mytail:
	$(CMD) mytail.c -o mytail

myls:
	$(CMD) myls.c -o myls

mytree:
	$(CMD) mytree.c -o mytree

mystat:
	$(CMD) mystat.c -o mystat

clean:
	rm $(OBJS)

